name: Read PR Description

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  print-description:
    runs-on: ubuntu-latest
    steps:
    - name: Print Entire GitHub Context
      run: echo "${{ toJson(github) }}"
      
    - name: Echo PR Description or Notify if Empty
      run: |
        if [[ -z "${{ github.event.pull_request.body }}" ]]; then
          echo "The PR description is empty."
        else
          echo "PR Description: ${{ github.event.pull_request.body }}"
        fi
        
    - name: Append commit to Changelog
      run: |
        echo "CHANGELOG: ${{ github.event.pull_request.body }}" >> CHANGELOG.md
            

    - name: Commit and push if it changed
      run: |
        git diff
        git config --global user.email "paripathak80@gmail.com"
        git config --global user.name "Himani1519"
        git commit -am "Update Changelog" -m " ${{ github.event.pull_request.body }}" && echo ::set-output name=push::true || echo "No changes to commit"
        git push origin || echo "No changes to push"
