name: "blank file"

on: 
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  print-pr-message:
    runs-on: ubuntu-latest
    steps:
    - name: Output PR message
      run: |
        echo "PR Message: ${{ github.event.pull_request.body }}"
