name: "blank file"

on: [push, pull_request]

jobs:
  print-pr-message:
    runs-on: ubuntu-latest
    steps:
    - name: Output PR message
      run: |
        echo "PR Message: ${{ github.event.pull_request.body }}"
