name: Update Changelog

on:
  pull_request:
    types:
      - opened

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Check if CHANGELOG was updated
        id: check-changelog
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          CHANGELOG_UPDATED=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/files | jq '[.[] | select(.filename=="CHANGELOG.md") | .status=="modified"] | any')
          echo "::set-output name=updated::$CHANGELOG_UPDATED"

      - name: Get PR commits
        id: pr
        if: ${{ steps.check-changelog.outputs.updated == 'false' }}
        uses: octokit/request-action@v2.x
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pull_number}/commits
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.pull_request.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract commit messages
        id: commits
        if: ${{ steps.check-changelog.outputs.updated == 'false' }}
        run: |
          COMMITS=${{ steps.pr.outputs.data }}
          COMMIT_MESSAGES=$(echo "$COMMITS" | jq -r '[.[] | .commit.message] | join("\n")')
          echo "COMMIT_MESSAGES=$COMMIT_MESSAGES" >> $GITHUB_ENV

      - name: Update Changelog
        if: ${{ steps.check-changelog.outputs.updated == 'false' }}
        run: |
          echo -e "$COMMIT_MESSAGES\n$(cat CHANGELOG.md)" > CHANGELOG.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"

      - name: Push changes
        if: ${{ steps.check-changelog.outputs.updated == 'false' }}
        uses: actions/checkout@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.event.pull_request.base.ref }}
