name: Read PR Description

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        
    - name: Get repo name
      run: |
        REPO_NAME="${{ github.event.pull_request.head.repo.name }}"
        PREFIX=$(echo "$REPO_NAME" | cut -d'/' -fi)
        echo "Repository Prefix: $PREFIX"

    - name: Append PR Description to Changelog
      run: |
        echo -e "\n## PR Description for #${{ github.event.pull_request.number }}" >> changelog.md
        echo "${{ github.event.pull_request.body }}" >> changelog.md

    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add changelog.md
        git commit -m "Update changelog with PR #${{ github.event.pull_request.number }} description"
        git push
