
name: Manage Changelog

on: [push, pull_request]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    outputs:
      wasUpdated: ${{ steps.set_output.outputs.wasUpdated }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2  # fetch last (current) and penultimate (previous) commit

      - name: Check if CHANGELOG.md was updated
        id: check
        run: |
          if git diff --name-only HEAD^ HEAD | grep 'CHANGELOG.md'; then
            echo "CHANGELOG.md was updated in the last commit."
            echo "::set-output name=was_updated::false"
          else
            echo "CHANGELOG.md was NOT updated in the last commit."
            echo "::set-output name=was_updated::true"
          fi


      - name: Update Changelog if necessary
        if: steps.check.outputs.wasUpdated == 'true'
        run: |
          # Your script or command to update the CHANGELOG.md
          git config --global user.name "Himani1519"
          git config --global user.email "paripathak80@gmail.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md"
          git push

      - name: Set output
        id: set_output
        run: echo "::set-output name=wasUpdated::$(git diff --name-only HEAD~1..HEAD | grep '^CHANGELOG.md$' && echo true || echo false)"

  verify-changelog:
    needs: update-changelog
    runs-on: ubuntu-latest
    if: needs.update-changelog.outputs.wasUpdated == 'true'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Verify CHANGELOG.md was updated
        run: |
          if git diff --name-only HEAD~1..HEAD | grep '^CHANGELOG.md$'; then
            echo "CHANGELOG.md was updated."
          else
            echo "CHANGELOG.md was not updated."
            exit 1
          fi
