name: Update Changelog

on: [push]

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get commit message
        run: echo "COMMIT_MESSAGE=$(git log --format=%B -n 1)" >> $GITHUB_ENV

      - name: Append commit to Changelog
        run: |
          echo "$COMMIT_MESSAGE" >> CHANGELOG.md

      - name: Commit and push if it changed
        run: |
          git diff
          git config --global user.email "paripathak80@gmail.com"
          git config --global user.name "Himani1519"
          git commit -am "Update Changelog" -m "$COMMIT_MESSAGE" && echo ::set-output name=push::true || echo "No changes to commit"
          git push origin || echo "No changes to push"
       
