name: "Test"

on: [push, pull_request]

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get commit message 
        id: commit
        run: |
           COMMIT_MESSAGE=$(git log --format=%B -n 1)
           echo "Commit message: $COMMIT_MESSAGE"
           echo "::set-output name=message::$COMMIT_MESSAGE"
           

      - name: update changelog
        id: set-flag
        run: |
            echo "${{ steps.commit.outputs.message }}" >>CHANGELOG.md
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add CHANGELOG.md
            git commit -m "update CHANGELOG.md"
            git push
