name: "File existence check"

on: [push, pull_request]

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            path: copy-repo
            fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Get changed files
        id: changed-files
        run: |
            cd copy-repo
            if ${{ github.event_name == 'pull_request' }}; then
                echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
            else
                echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
            fi

      - name: List changed files
        id: set-flag
        run: |
            cd copy-repo
            for file in ${{ steps.changed-files.outputs.changed_files }}; do
                echo "$file was changed"
                if [[ $file == "CHANGELOG.md" ]]
                then
                  echo "file-flag=true" >> $GITHUB_OUTPUT
                  break;
                else
                  echo "file-flag=false" >> $GITHUB_OUTPUT
                fi
            done
            
      - name : Get PR commits
        id: pr
        with:
          route: GET /repos/{owner}/{repo}/pulls/{pull_number}/commits
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          pull_number: ${{ github.event.pull_request.number }}
          run: |
            echo "Got the PR commits"
        
      - name: Extract Changelog
        id: changelog
        run: |
          COMMIT_DATA=${{ steps.pr.outputs.data }}
          #commmit message 
          COMMIT_MESSAGE=$(echo "$COMMIT_DATA" |jq '.[-1].commit.essage' -r)
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >>$GITHUB_ENV
      
      - name: update changelog if not updated
        if: steps.set-flag.outputs.file-flag != 'true'
        run: |
          echo "$COMMIT_MESSAGE" >> CHANGELOG.md
          git config --local user.email "paripathak80@gmail.com"
          git config --local user.name "Himani1519"
          git commit -m  "Update changelog" -a
        
      - name: Push changes
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run: |
            echo "Pushed the changes"
          
  check_changelog:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
              path: copy-repo
              fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

        - name: Get changed files
          id: changed-files
          run: |
              cd copy-repo
              if ${{ github.event_name == 'pull_request' }}; then
                  echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
              else
                  echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
              fi

        - name: List changed files
          id: set-flag
          run: |
              cd copy-repo
              for file in ${{ steps.changed-files.outputs.changed_files }}; do
                  echo "$file was changed"
                  if [[ $file == "CHANGELOG.md" ]]
                  then
                    echo "file-flag=true" >> $GITHUB_OUTPUT
                    break;
                  else
                    echo "file-flag=false" >> $GITHUB_OUTPUT
                  fi
              done

        - name: Check if CHANGELOG is Updated and Abort if CHANGELOG is not updated
          if: steps.set-flag.outputs.file-flag != 'true'
          run: |
            echo "CHANGELOG not added. Please add the CHANGELOG in the CHANGELOG.md file"
        
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
