name: "File existence check"

on: [push, pull_request]

jobs:
  check_changelog:
    runs-on: ubuntu-latest
    outputs:
        was_updated: ${{ steps.check.outputs.was_updated }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            path: copy-repo
            fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}

      - name: Check if CHANGELOG.md was updated
        id: check
        run: |
          if git diff --name-only HEAD^ HEAD | grep 'CHANGELOG.md'; then
            echo "CHANGELOG.md was updated in the last commit."
            echo "::set-output name=was_updated::true"
          else
            echo "CHANGELOG.md was NOT updated in the last commit."
            echo "::set-output name=was_updated::false"
          fi

      - name: Check if CHANGELOG is Updated and Abort if not updated
        if: ${{ steps.check.outputs.was_updated != 'true' }}
        run: |
          echo "CHANGELOG not added. Please add the CHANGELOG in the CHANGELOG.md file"
          
    
  update_changelog:
      needs: check_changelog
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          if: ${{ needs.check_changelog.outputs.was_updated == 'false' }}
          uses: actions/checkout@v2
          with:
            fetch-depth: 2

        - name: Get commit message
          if: ${{ needs.check_changelog.outputs.was_updated == 'false' }}
          run: echo "COMMIT_MESSAGE=$(git log --format=%B -n 1)" >> $GITHUB_ENV
      

        - name: Append commit to Changelog
          if: ${{ needs.check_changelog.outputs.was_updated == 'false' }}
          run: |
            echo "CHANGELOG: $COMMIT_MESSAGE" >> CHANGELOG.md
            echo "${{ steps.check-changelog.outputs.was_updated}}"
            

        - name: Commit and push if it changed
          if: ${{ needs.check_changelog.outputs.was_updated == 'false' }}
          run: |
            git diff
            git config --global user.email "paripathak80@gmail.com"
            git config --global user.name "Himani1519"
            git commit -am "Update Changelog" -m "$COMMIT_MESSAGE" && echo ::set-output name=push::true || echo "No changes to commit"
            git push origin || echo "No changes to push"
          

        
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
